
on:
  push:
    branches:
      - main
env:
  GITURL: ${{ secrets.APP_SVC_GIT_URL }}
  MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      
    - name: 'Deploy to Web'
      run: |
        git clone "$GITURL"
        rsync -av . ./nh4hgrap --exclude nh4hgrap --exclude .github
        cd nh4hgrap
        git config user.email "gh@auto.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "$MESSAGE"
        git push