
on:
  push:
    branches:
      - main
env:
  GITURL: ${{ secrets.GITURL }}
  MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
          
    - name: 'Stage files'
      run: |
        git clone "$GITURL"
        rsync -av . ./nh4hgrap --exclude nh4hgrap --exclude .github --exclude .git
    - name: 'Deploy to Web'
      run: |
        cd nh4hgrap
        pwd
        git config user.email "gh@auto.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "$MESSAGE"
        git push